"""Generate a visual diagram of the Movie Finder LangGraph chain.

## Enterprise standard approach
LangGraph compiles the graph into a data structure that can be serialised as
Mermaid — a text-based diagram language rendered natively by GitHub, GitLab,
Confluence (via plugin), and Notion.  Generating from the compiled graph (not
hand-written) guarantees the diagram is *always* in sync with the code.

## Outputs
1. ``docs/chain_diagram.md``   — Mermaid fenced block, embed in any doc tool
2. ``docs/chain_diagram.png``  — PNG raster, drop into slides / Confluence pages
   (requires the ``Pillow`` extra: ``uv pip install langgraph[draw]``)

## Usage
    # from the chain/ package root
    uv run python scripts/generate_diagram.py

    # skip PNG (no Pillow / graphviz installed)
    uv run python scripts/generate_diagram.py --no-png
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Stub out the required env vars so ChainConfig validates without real values.
# Nodes are never executed here — we only compile the graph structure.
# ---------------------------------------------------------------------------
_STUBS: dict[str, str] = {
    "QDRANT_URL": "https://stub.qdrant.io",
    "QDRANT_API_KEY_RO": "stub",  # pragma: allowlist secret
    "OPENAI_API_KEY": "stub",  # pragma: allowlist secret
    "ANTHROPIC_API_KEY": "stub",  # pragma: allowlist secret
}
for _key, _val in _STUBS.items():
    os.environ.setdefault(_key, _val)

# Add src/ to sys.path so the package is importable without an install step.
_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from chain import compile_graph  # noqa: E402  (import after path manipulation)


def main(*, write_png: bool = True) -> None:
    docs_dir = _ROOT / "docs"
    docs_dir.mkdir(exist_ok=True)

    graph = compile_graph()
    draw = graph.get_graph(xray=True)  # xray=True expands subgraphs

    # ------------------------------------------------------------------ #
    # 1. Mermaid text  (primary artefact — version-controlled)
    # ------------------------------------------------------------------ #
    mermaid_text: str = draw.draw_mermaid()

    md_path = docs_dir / "chain_diagram.md"
    md_path.write_text(
        "# Movie Finder — Chain Diagram\n\n"
        "> Auto-generated by `scripts/generate_diagram.py`."
        "  Do **not** edit by hand.\n\n"
        f"```mermaid\n{mermaid_text}\n```\n",
        encoding="utf-8",
    )
    print(f"[ok] Mermaid diagram written to  {md_path.relative_to(_ROOT)}")

    # ------------------------------------------------------------------ #
    # 2. PNG raster  (for slides / Confluence attachments)
    # ------------------------------------------------------------------ #
    if write_png:
        try:
            from langgraph.graph.mermaid import MermaidDrawMethod

            png_bytes: bytes = draw.draw_mermaid_png(
                draw_method=MermaidDrawMethod.PYPPETEER,  # renders locally, no internet needed
            )
            png_path = docs_dir / "chain_diagram.png"
            png_path.write_bytes(png_bytes)
            print(f"[ok] PNG diagram written to      {png_path.relative_to(_ROOT)}")
        except ImportError:
            # PYPPETEER not installed — fall back to mermaid.ink (requires internet)
            try:
                png_bytes = draw.draw_mermaid_png(max_retries=3, retry_delay=2.0)
                png_path = docs_dir / "chain_diagram.png"
                png_path.write_bytes(png_bytes)
                print(f"[ok] PNG diagram written to      {png_path.relative_to(_ROOT)}")
            except Exception as exc2:  # noqa: BLE001
                print(
                    f"[warn] PNG generation skipped: {exc2}\n"
                    "       For local rendering: uv pip install pyppeteer\n"
                    "       For cloud rendering: ensure internet access to mermaid.ink",
                    file=sys.stderr,
                )
        except Exception as exc:  # noqa: BLE001
            print(f"[warn] PNG generation skipped: {exc}", file=sys.stderr)

    # ------------------------------------------------------------------ #
    # 3. Print the Mermaid source to stdout for quick inspection
    # ------------------------------------------------------------------ #
    print("\n--- Mermaid source ---")
    print(mermaid_text)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--no-png", dest="png", action="store_false", help="Skip PNG generation")
    args = parser.parse_args()
    main(write_png=args.png)
